# CONFIGURATION
# Rohbau3D

# GENERAL
config_dir: config
log_dir: log
log_level: INFO

# DOWNLOAD
download_hub: dataverse
download_dir: data/download
feature_index_file: dataverse_file_index.json
feature_selection: [all]
scene_selection: [all]

# FILE EXTRACT
extract_dir: data/extract
clean_download_files: False

